package GUI;

import Utils.ProblemesModel;
import Utils.SoluModel;
import entities.Probleme;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.nio.file.Path;
import java.sql.Date;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import java.io.FileOutputStream;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author asalhi
 */
public class JFrameProblem extends javax.swing.JFrame {

    public static File file;
    public int num;
    public String filePath;
    public String fileName;

    public JFrameProblem() {
        setTitle("CrowdRise");

        initComponents();
        jTxtFldUID.setVisible(false);
        jLabelUID.setVisible(false);
        jBtnSupprimer.setToolTipText("Supprimer");
        jBtnModifier.setToolTipText("Modifier");

    }

    public void setLay() {
        jTableDemandes.setModel(new ProblemesModel());
        jScrollPane2.setViewportView(jTableDemandes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jFileChooserProb = new javax.swing.JFileChooser();
        jPanelExterne = new javax.swing.JPanel();
        jTabbedPaneGestionDemande = new javax.swing.JTabbedPane();
        jPanelAjout = new javax.swing.JPanel();
        jTxtFldDeposer = new javax.swing.JTextField();
        jLabelTitreProb = new javax.swing.JLabel();
        jTxtFldTitreProb = new javax.swing.JTextField();
        jLabelCateg = new javax.swing.JLabel();
        jComboCategorie = new javax.swing.JComboBox();
        jLabelDeadline = new javax.swing.JLabel();
        jDtChooserDeadline = new com.toedter.calendar.JDateChooser();
        jLabelFichier = new javax.swing.JLabel();
        jTxtFldFichier = new javax.swing.JTextField();
        jBtnJoindreFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAreaDescription = new javax.swing.JTextArea();
        jBtnDeposer = new javax.swing.JButton();
        jLabelDescription = new javax.swing.JLabel();
        jLabelUID = new javax.swing.JLabel();
        jTxtFldUID = new javax.swing.JTextField();
        jPanelConsulter = new javax.swing.JPanel();
        jTxtFldListeDemandes = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDemandes = new javax.swing.JTable();
        jBtnSupprimer = new javax.swing.JButton();
        jBtnModifier = new javax.swing.JButton();
        jLabelFileDw = new javax.swing.JLabel();
        jBtnDownLoadProblem = new javax.swing.JButton();
        jTxtFldSearchTitre = new javax.swing.JTextField();
        jDateChooserSearch = new com.toedter.calendar.JDateChooser();
        jCmboCategSearch = new javax.swing.JComboBox();
        jBtnSearch = new javax.swing.JButton();
        jPanelSolutions = new javax.swing.JPanel();
        jTxtFldListeDemandes1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProbSol = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableSolution = new javax.swing.JTable();
        jBtnAccepter = new javax.swing.JButton();
        jBtnRefuser = new javax.swing.JButton();
        jPanelSolAcceptees = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableSolAccepte = new javax.swing.JTable();
        jLabelSolDwn = new javax.swing.JLabel();
        jBtnDownLoadSolution = new javax.swing.JButton();
        jBtnSupprimSolAccepte = new javax.swing.JButton();
        jPanelSolRefus = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableSolRejete = new javax.swing.JTable();
        jBtnSupprimSolRejete = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuOptions = new javax.swing.JMenu();
        jMenuItemDemande = new javax.swing.JMenuItem();
        jMenuItemContact = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenuItem();
        JMenuApropos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelExterne.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")), "Gestion des Demandes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 24), new java.awt.Color(0, 51, 255))); // NOI18N
        jPanelExterne.setLayout(null);

        jTabbedPaneGestionDemande.setForeground(new java.awt.Color(1, 139, 1));

        jPanelAjout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTxtFldDeposer.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jTxtFldDeposer.setText(" Déposez votre demande ");
        jTxtFldDeposer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldDeposerActionPerformed(evt);
            }
        });

        jLabelTitreProb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelTitreProb.setText("Titre :");

        jTxtFldTitreProb.setText("");
        jTxtFldTitreProb.setToolTipText("* Champ obligatoire");

        jLabelCateg.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelCateg.setText("Catégorie :");

        jComboCategorie.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboCategorie.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"",  "Financier", "Administratif", "Technique", "Marketing","Social","Autre" }));
        jComboCategorie.setToolTipText("");

        jLabelDeadline.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelDeadline.setText("DeadLine :");

        jDtChooserDeadline.setToolTipText("* Champ obligatoire ");
        jDtChooserDeadline.setDateFormatString("dd/MM/yyyy");
        jDtChooserDeadline.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDtChooserDeadline.setMinSelectableDate(new java.util.Date(-62135769537000L));
        jDtChooserDeadline.setOpaque(false);

        jLabelFichier.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelFichier.setText("Fichier :");

        jTxtFldFichier.setText(" ");

        jBtnJoindreFile.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnJoindreFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/attach_file.png"))); // NOI18N
        jBtnJoindreFile.setText("Joindre");
        jBtnJoindreFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnJoindreFileActionPerformed(evt);
            }
        });

        jTxtAreaDescription.setColumns(20);
        jTxtAreaDescription.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTxtAreaDescription.setRows(5);
        jTxtAreaDescription.setToolTipText("* Champ obligatoire");
        jScrollPane1.setViewportView(jTxtAreaDescription);

        jBtnDeposer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnDeposer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/depos.png"))); // NOI18N
        jBtnDeposer.setText("Déposer");
        jBtnDeposer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeposerActionPerformed(evt);
            }
        });

        jLabelDescription.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelDescription.setText("Description :");

        jLabelUID.setText("UID");

        jTxtFldUID.setText(" ");

        javax.swing.GroupLayout jPanelAjoutLayout = new javax.swing.GroupLayout(jPanelAjout);
        jPanelAjout.setLayout(jPanelAjoutLayout);
        jPanelAjoutLayout.setHorizontalGroup(
            jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjoutLayout.createSequentialGroup()
                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAjoutLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jTxtFldDeposer, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAjoutLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitreProb, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAjoutLayout.createSequentialGroup()
                                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtFldTitreProb, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDtChooserDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(95, 95, 95)
                                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelAjoutLayout.createSequentialGroup()
                                        .addComponent(jLabelCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jComboCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelAjoutLayout.createSequentialGroup()
                                        .addComponent(jLabelFichier, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTxtFldFichier)))
                                .addGap(18, 18, 18)
                                .addComponent(jBtnJoindreFile))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelAjoutLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabelUID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtFldUID, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248)
                        .addComponent(jBtnDeposer, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanelAjoutLayout.setVerticalGroup(
            jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAjoutLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jTxtFldDeposer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtFldTitreProb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTitreProb))
                    .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCateg)))
                .addGap(46, 46, 46)
                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelFichier, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtFldFichier, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnJoindreFile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDtChooserDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAjoutLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanelAjoutLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnDeposer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelUID)
                        .addComponent(jTxtFldUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );

        jTabbedPaneGestionDemande.addTab("Ajouter Demande", jPanelAjout);

        jPanelConsulter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelConsulter.setLayout(null);

        jTxtFldListeDemandes.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jTxtFldListeDemandes.setText(" Liste des demandes");
        jTxtFldListeDemandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldListeDemandesActionPerformed(evt);
            }
        });
        jPanelConsulter.add(jTxtFldListeDemandes);
        jTxtFldListeDemandes.setBounds(350, 10, 210, 34);

        jTableDemandes.setModel(new Utils.ProblemesModel());
        jScrollPane2.setViewportView(jTableDemandes);

        jPanelConsulter.add(jScrollPane2);
        jScrollPane2.setBounds(80, 140, 670, 260);

        jBtnSupprimer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jBtnSupprimer.setText("Supprimer");
        jBtnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSupprimerActionPerformed(evt);
            }
        });
        jPanelConsulter.add(jBtnSupprimer);
        jBtnSupprimer.setBounds(530, 420, 130, 30);

        jBtnModifier.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Modifier.png"))); // NOI18N
        jBtnModifier.setText("Modifier");
        jBtnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModifierActionPerformed(evt);
            }
        });
        jPanelConsulter.add(jBtnModifier);
        jBtnModifier.setBounds(380, 420, 110, 30);

        jLabelFileDw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/File.png"))); // NOI18N
        jLabelFileDw.setText(" ");
        jPanelConsulter.add(jLabelFileDw);
        jLabelFileDw.setBounds(810, 160, 60, 80);

        jBtnDownLoadProblem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnDownLoadProblem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download.png"))); // NOI18N
        jBtnDownLoadProblem.setText("Télécharger");
        jBtnDownLoadProblem.setToolTipText("Télécharger Fichier");
        jBtnDownLoadProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDownLoadProblemActionPerformed(evt);
            }
        });
        jPanelConsulter.add(jBtnDownLoadProblem);
        jBtnDownLoadProblem.setBounds(790, 260, 120, 25);

        jTxtFldSearchTitre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTxtFldSearchTitre.setForeground(new java.awt.Color(153, 153, 153));
        jTxtFldSearchTitre.setText("Titre");
        jTxtFldSearchTitre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtFldSearchTitreMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTxtFldSearchTitreMouseExited(evt);
            }
        });
        jTxtFldSearchTitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldSearchTitreActionPerformed(evt);
            }
        });
        jPanelConsulter.add(jTxtFldSearchTitre);
        jTxtFldSearchTitre.setBounds(100, 90, 180, 30);

        jDateChooserSearch.setDateFormatString("dd/MM/yyyy");
        jDateChooserSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanelConsulter.add(jDateChooserSearch);
        jDateChooserSearch.setBounds(300, 90, 140, 30);

        jCmboCategSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCmboCategSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Financier", "Administratif", "Technique", "Marketing","Social","Autre"}));
        jCmboCategSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmboCategSearchActionPerformed(evt);
            }
        });
        jPanelConsulter.add(jCmboCategSearch);
        jCmboCategSearch.setBounds(460, 90, 130, 30);

        jBtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jBtnSearch.setText("Chercher");
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });
        jPanelConsulter.add(jBtnSearch);
        jBtnSearch.setBounds(620, 90, 110, 30);

        jTabbedPaneGestionDemande.addTab("Consulter Demandes", jPanelConsulter);

        jPanelSolutions.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelSolutions.setLayout(null);

        jTxtFldListeDemandes1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jTxtFldListeDemandes1.setText(" Liste des solutions proposés");
        jTxtFldListeDemandes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldListeDemandes1ActionPerformed(evt);
            }
        });
        jPanelSolutions.add(jTxtFldListeDemandes1);
        jTxtFldListeDemandes1.setBounds(300, 10, 300, 34);

        jTableProbSol.setModel(new Utils.ProbModel());
        jTableProbSol.setToolTipText("Les demandes");
        jTableProbSol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProbSolMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableProbSol);

        jPanelSolutions.add(jScrollPane3);
        jScrollPane3.setBounds(30, 100, 260, 260);

        jTableSolution.setModel(new Utils.SoluModel());
        jTableSolution.setToolTipText("Les solutions proposés");
        jScrollPane4.setViewportView(jTableSolution);

        jPanelSolutions.add(jScrollPane4);
        jScrollPane4.setBounds(350, 100, 550, 260);

        jBtnAccepter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnAccepter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Accept.png"))); // NOI18N
        jBtnAccepter.setText("Accepter");
        jBtnAccepter.setToolTipText("Accpter la solution");
        jBtnAccepter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAccepterActionPerformed(evt);
            }
        });
        jPanelSolutions.add(jBtnAccepter);
        jBtnAccepter.setBounds(490, 400, 110, 30);

        jBtnRefuser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnRefuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Erase.png"))); // NOI18N
        jBtnRefuser.setText("Refuser");
        jBtnRefuser.setToolTipText("Refuser la solution");
        jBtnRefuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRefuserActionPerformed(evt);
            }
        });
        jPanelSolutions.add(jBtnRefuser);
        jBtnRefuser.setBounds(630, 400, 100, 30);

        jTabbedPaneGestionDemande.addTab("Solutions", jPanelSolutions);

        jPanelSolAcceptees.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));

        jTableSolAccepte.setModel(new Utils.SoluModel("Accepte"));
        jScrollPane5.setViewportView(jTableSolAccepte);

        jLabelSolDwn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/File.png"))); // NOI18N
        jLabelSolDwn.setText(" ");

        jBtnDownLoadSolution.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnDownLoadSolution.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download.png"))); // NOI18N
        jBtnDownLoadSolution.setText("Télécharger");
        jBtnDownLoadSolution.setToolTipText("Télécharger la solution");
        jBtnDownLoadSolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDownLoadSolutionActionPerformed(evt);
            }
        });

        jBtnSupprimSolAccepte.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnSupprimSolAccepte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jBtnSupprimSolAccepte.setText("Supprimer");
        jBtnSupprimSolAccepte.setToolTipText("Supprimer");
        jBtnSupprimSolAccepte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSupprimSolAccepteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSolAccepteesLayout = new javax.swing.GroupLayout(jPanelSolAcceptees);
        jPanelSolAcceptees.setLayout(jPanelSolAccepteesLayout);
        jPanelSolAccepteesLayout.setHorizontalGroup(
            jPanelSolAccepteesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSolAccepteesLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanelSolAccepteesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSolAccepteesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelSolDwn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnDownLoadSolution, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(jPanelSolAccepteesLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jBtnSupprimSolAccepte, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSolAccepteesLayout.setVerticalGroup(
            jPanelSolAccepteesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSolAccepteesLayout.createSequentialGroup()
                .addGroup(jPanelSolAccepteesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSolAccepteesLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabelSolDwn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jBtnDownLoadSolution))
                    .addGroup(jPanelSolAccepteesLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jBtnSupprimSolAccepte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPaneGestionDemande.addTab("Solutions Acceptées", jPanelSolAcceptees);

        jPanelSolRefus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));

        jTableSolRejete.setModel(new Utils.SoluModel("Refuse"));
        jScrollPane6.setViewportView(jTableSolRejete);

        jBtnSupprimSolRejete.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnSupprimSolRejete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jBtnSupprimSolRejete.setText("Supprimer");
        jBtnSupprimSolRejete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSupprimSolRejeteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSolRefusLayout = new javax.swing.GroupLayout(jPanelSolRefus);
        jPanelSolRefus.setLayout(jPanelSolRefusLayout);
        jPanelSolRefusLayout.setHorizontalGroup(
            jPanelSolRefusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSolRefusLayout.createSequentialGroup()
                .addGroup(jPanelSolRefusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSolRefusLayout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jBtnSupprimSolRejete, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSolRefusLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanelSolRefusLayout.setVerticalGroup(
            jPanelSolRefusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSolRefusLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jBtnSupprimSolRejete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPaneGestionDemande.addTab("Solutions Rejetées", jPanelSolRefus);

        jPanelExterne.add(jTabbedPaneGestionDemande);
        jTabbedPaneGestionDemande.setBounds(10, 50, 940, 500);

        getContentPane().add(jPanelExterne);
        jPanelExterne.setBounds(10, 20, 960, 570);

        jMenuOptions.setText("Options");

        jMenuItemDemande.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemDemande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/suppliers.png"))); // NOI18N
        jMenuItemDemande.setText("Demande");
        jMenuItemDemande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDemandeActionPerformed(evt);
            }
        });
        jMenuOptions.add(jMenuItemDemande);

        jMenuItemContact.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contact.png"))); // NOI18N
        jMenuItemContact.setText("Contact");
        jMenuItemContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContactActionPerformed(evt);
            }
        });
        jMenuOptions.add(jMenuItemContact);

        jMenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenuOptions.add(jMenuExit);

        jMenuBar.add(jMenuOptions);

        JMenuApropos.setText("A propos");
        jMenuBar.add(JMenuApropos);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        int action = JOptionPane.showConfirmDialog(JFrameProblem.this, "Are you sure to exit! ", "Confirm Exit", JOptionPane.OK_CANCEL_OPTION);

        if (action == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jMenuItemDemandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDemandeActionPerformed
        this.setVisible(true);
    }//GEN-LAST:event_jMenuItemDemandeActionPerformed

    private void jTxtFldDeposerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldDeposerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldDeposerActionPerformed

    private void jTxtFldListeDemandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldListeDemandesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldListeDemandesActionPerformed

    private void jTxtFldListeDemandes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldListeDemandes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldListeDemandes1ActionPerformed

    private void jMenuItemContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContactActionPerformed
        try {
            new JFrameContact().setVisible(true);
        } catch (MessagingException ex) {
            Logger.getLogger(JFrameProblem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemContactActionPerformed

    private void jBtnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSupprimerActionPerformed
        int action = JOptionPane.showConfirmDialog(JFrameProblem.this, "Voulez vous vraiment terminer la suppression ! ", "Confirmation Suppression", JOptionPane.OK_CANCEL_OPTION);

        if (action == JOptionPane.OK_OPTION) {
            new dao.Problemedao().removeById((int) jTableDemandes.getValueAt(jTableDemandes.getSelectedRow(), 0));
            setLay();
        }


    }//GEN-LAST:event_jBtnSupprimerActionPerformed

    private void jBtnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModifierActionPerformed

        int ID = (int) jTableDemandes.getValueAt(jTableDemandes.getSelectedRow(), 0);
        String titre = (String) jTableDemandes.getValueAt(jTableDemandes.getSelectedRow(), 1);
        String categorie = (String) jTableDemandes.getValueAt(jTableDemandes.getSelectedRow(), 2);
        Date deadline = (Date) jTableDemandes.getValueAt(jTableDemandes.getSelectedRow(), 3);
        String description = (String) jTableDemandes.getValueAt(jTableDemandes.getSelectedRow(), 4);
        String fichier = (String) jTableDemandes.getValueAt(jTableDemandes.getSelectedRow(), 5);

        JFrameEditProblem jFrameEditProblem = new JFrameEditProblem(this);
        jFrameEditProblem.setVisible(true);

        jFrameEditProblem.getjTxtFldIDProb().setText(String.valueOf(ID));
        jFrameEditProblem.getjTxtFldTitreProb().setText(titre);
        jFrameEditProblem.getjComboCategorie().setSelectedItem(categorie);
        jFrameEditProblem.getjDtChooserDeadline().setDate(deadline);
        jFrameEditProblem.getjTextArea1().setText(description);
        jFrameEditProblem.getjTxtFldFichier().setText(fichier);

        jFrameEditProblem.setBounds(250, 250, 1000, 700);

    }//GEN-LAST:event_jBtnModifierActionPerformed

    private void jBtnJoindreFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnJoindreFileActionPerformed
        int returnVal = jFileChooserProb.showOpenDialog(this);
        if (returnVal == jFileChooserProb.APPROVE_OPTION) {
            file = jFileChooserProb.getSelectedFile();

            filePath = file.getAbsolutePath();
            fileName = filePath.substring(filePath.lastIndexOf(File.separator) + 1);

            num = new dao.Problemedao().getFileNumber();

            jTxtFldFichier.setText(fileName);
        }
        jFileChooserProb.setVisible(true);
    }//GEN-LAST:event_jBtnJoindreFileActionPerformed

    private void jBtnAccepterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAccepterActionPerformed

        int IDSol = (int) jTableSolution.getValueAt(jTableSolution.getSelectedRow(), 0);
        new dao.Problemedao().updateSolAccepte("Accepte", IDSol);

        JOptionPane.showMessageDialog(this, "Solution Acceptée",
                " Congratulation :)", JOptionPane.INFORMATION_MESSAGE);

        jTableSolution.setModel(new SoluModel((int) jTableProbSol.getValueAt(jTableProbSol.getSelectedRow(), 0)));
        jScrollPane4.setViewportView(jTableSolution);

        jTableSolAccepte.setModel(new SoluModel("Accepte"));
        jScrollPane5.setViewportView(jTableSolAccepte);

    }//GEN-LAST:event_jBtnAccepterActionPerformed

    private void jBtnRefuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRefuserActionPerformed

        int IDSol = (int) jTableSolution.getValueAt(jTableSolution.getSelectedRow(), 0);
        new dao.Problemedao().updateSolAccepte("Refuse", IDSol);

        JOptionPane.showMessageDialog(this, "Solution Refusée",
                " Refus :(", JOptionPane.ERROR_MESSAGE);

        jTableSolution.setModel(new SoluModel((int) jTableProbSol.getValueAt(jTableProbSol.getSelectedRow(), 0)));
        jScrollPane4.setViewportView(jTableSolution);

        jTableSolRejete.setModel(new SoluModel("Refuse"));
        jScrollPane6.setViewportView(jTableSolRejete);


    }//GEN-LAST:event_jBtnRefuserActionPerformed

    private void jBtnSupprimSolAccepteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSupprimSolAccepteActionPerformed
        int action = JOptionPane.showConfirmDialog(JFrameProblem.this, "Voulez vous vraiment terminer la suppression ! ", "Confirmation Suppression", JOptionPane.OK_CANCEL_OPTION);

        if (action == JOptionPane.OK_OPTION) {
            new dao.Problemedao().removeByIdSol((int) jTableSolAccepte.getValueAt(jTableSolAccepte.getSelectedRow(), 0));
            jTableSolAccepte.setModel(new SoluModel("Accepte"));
            jScrollPane5.setViewportView(jTableSolAccepte);
        }

    }//GEN-LAST:event_jBtnSupprimSolAccepteActionPerformed

    private void jBtnSupprimSolRejeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSupprimSolRejeteActionPerformed
        int action = JOptionPane.showConfirmDialog(JFrameProblem.this, "Voulez vous vraiment terminer la suppression ! ", "Confirmation Suppression", JOptionPane.OK_CANCEL_OPTION);

        if (action == JOptionPane.OK_OPTION) {
            new dao.Problemedao().removeByIdSol((int) jTableSolRejete.getValueAt(jTableSolRejete.getSelectedRow(), 0));

            jTableSolRejete.setModel(new SoluModel("Refuse"));
            jScrollPane6.setViewportView(jTableSolRejete);
        }


    }//GEN-LAST:event_jBtnSupprimSolRejeteActionPerformed

    private void jTableProbSolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProbSolMouseClicked

        jTableSolution.setModel(new SoluModel((int) jTableProbSol.getValueAt(jTableProbSol.getSelectedRow(), 0)));
        jScrollPane4.setViewportView(jTableSolution);
    }//GEN-LAST:event_jTableProbSolMouseClicked

    private void jCmboCategSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmboCategSearchActionPerformed

    }//GEN-LAST:event_jCmboCategSearchActionPerformed

    private void jTxtFldSearchTitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldSearchTitreActionPerformed

    }//GEN-LAST:event_jTxtFldSearchTitreActionPerformed

    private void jBtnDeposerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeposerActionPerformed
        if (jTxtFldTitreProb.getText() == null || jTxtFldTitreProb.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Le champ Titre est obligatoire", "", JOptionPane.WARNING_MESSAGE);
        } else if (jTxtAreaDescription.getText() == null || jTxtAreaDescription.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Le champ description est obligatoire", "", JOptionPane.WARNING_MESSAGE);
        } else if (jDtChooserDeadline.getDate() == null || jDtChooserDeadline.getDate().equals("")) {
            JOptionPane.showMessageDialog(this, "Le champ Deadline est obligatoire", "", JOptionPane.WARNING_MESSAGE);
        }else if (jDtChooserDeadline.getDate() != null && jDtChooserDeadline.getDate().before(new java.util.Date())) {
            JOptionPane.showMessageDialog(this, "Vous devez insérer une date valide", "", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Probleme p = new Probleme(WIDTH, jTxtFldTitreProb.getText(), jTxtAreaDescription.getText(),
                        jDtChooserDeadline.getDate(), String.valueOf(num+1), jComboCategorie.getSelectedItem().toString());
                
                new dao.Problemedao().addToMedia(num + 1, fileName, filePath);
                new dao.Problemedao().uploadFile(filePath,"C:\\xampp\\htdocs\\Pidev\\web\\uploads\\" + fileName );
                new dao.Problemedao().add(p);
                JOptionPane.showMessageDialog(this, "Insertion effectuée avec succès", "Ajout Demande", JOptionPane.INFORMATION_MESSAGE);
                jTxtFldTitreProb.setText("");
                jTxtAreaDescription.setText("");
                jDtChooserDeadline.setDate(null);
                jComboCategorie.setSelectedItem(null);
                jTxtFldFichier.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Insertion non effectuée", "Ajout Demande", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_jBtnDeposerActionPerformed

    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed

        jTableDemandes.setModel(new Utils.ProblemesModel(jTxtFldSearchTitre.getText(), jDateChooserSearch.getDate(),
                jCmboCategSearch.getSelectedItem().toString()));

        jScrollPane2.setViewportView(jTableDemandes);
    }//GEN-LAST:event_jBtnSearchActionPerformed

    private void jTxtFldSearchTitreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtFldSearchTitreMouseClicked

        jTxtFldSearchTitre.setText("");
        jTxtFldSearchTitre.setForeground(Color.BLACK);
    }//GEN-LAST:event_jTxtFldSearchTitreMouseClicked

    private void jTxtFldSearchTitreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtFldSearchTitreMouseExited

    }//GEN-LAST:event_jTxtFldSearchTitreMouseExited

    private void jBtnDownLoadProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDownLoadProblemActionPerformed
        String fileName = (String) jTableDemandes.getValueAt(jTableDemandes.getSelectedRow(), 5);
        String filePath = "C:\\xampp\\htdocs\\Pidev\\web\\uploads\\" + fileName;       
        new dao.Problemedao().uploadFile(filePath,"C:\\Users\\asalhi\\Downloads\\" + fileName );
                
        displayNotification("Téléchargement terminé avec succès!");
    }//GEN-LAST:event_jBtnDownLoadProblemActionPerformed

    /**telecharger solution
     * changer type de fichier_solution -> BD en int 
     * changer requete find allsol comme find all prob 
     * pour recuperer id du fichier et chercher ds la table media le path
     * pour telecharger et afficher le nom ds le tab
     */ 
    private void jBtnDownLoadSolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDownLoadSolutionActionPerformed
       String fileName = (String) jTableSolAccepte.getValueAt(jTableSolAccepte.getSelectedRow(), 4);
        String filePath = "C:\\wamp\\www\\Uploads\\Solutions\\" + fileName;       
        new dao.Problemedao().uploadFile(filePath,"C:\\Users\\asalhi\\Downloads\\" + fileName );
                
        displayNotification("Téléchargement terminé avec succès!");
    }//GEN-LAST:event_jBtnDownLoadSolutionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JFrameProblem frameProbleme = new JFrameProblem();
                frameProbleme.setBounds(250, 100, 1000, 700);
                frameProbleme.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuApropos;
    private javax.swing.JButton jBtnAccepter;
    private javax.swing.JButton jBtnDeposer;
    private javax.swing.JButton jBtnDownLoadProblem;
    private javax.swing.JButton jBtnDownLoadSolution;
    private javax.swing.JButton jBtnJoindreFile;
    private javax.swing.JButton jBtnModifier;
    private javax.swing.JButton jBtnRefuser;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JButton jBtnSupprimSolAccepte;
    private javax.swing.JButton jBtnSupprimSolRejete;
    private javax.swing.JButton jBtnSupprimer;
    private javax.swing.JComboBox jCmboCategSearch;
    private javax.swing.JComboBox jComboCategorie;
    private com.toedter.calendar.JDateChooser jDateChooserSearch;
    private com.toedter.calendar.JDateChooser jDtChooserDeadline;
    private javax.swing.JFileChooser jFileChooserProb;
    private javax.swing.JLabel jLabelCateg;
    private javax.swing.JLabel jLabelDeadline;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelFichier;
    private javax.swing.JLabel jLabelFileDw;
    private javax.swing.JLabel jLabelSolDwn;
    private javax.swing.JLabel jLabelTitreProb;
    private javax.swing.JLabel jLabelUID;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenuItem jMenuItemContact;
    private javax.swing.JMenuItem jMenuItemDemande;
    private javax.swing.JMenu jMenuOptions;
    private javax.swing.JPanel jPanelAjout;
    private javax.swing.JPanel jPanelConsulter;
    private javax.swing.JPanel jPanelExterne;
    private javax.swing.JPanel jPanelSolAcceptees;
    private javax.swing.JPanel jPanelSolRefus;
    private javax.swing.JPanel jPanelSolutions;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPaneGestionDemande;
    private javax.swing.JTable jTableDemandes;
    private javax.swing.JTable jTableProbSol;
    private javax.swing.JTable jTableSolAccepte;
    private javax.swing.JTable jTableSolRejete;
    private javax.swing.JTable jTableSolution;
    private javax.swing.JTextArea jTxtAreaDescription;
    private javax.swing.JTextField jTxtFldDeposer;
    private javax.swing.JTextField jTxtFldFichier;
    private javax.swing.JTextField jTxtFldListeDemandes;
    private javax.swing.JTextField jTxtFldListeDemandes1;
    private javax.swing.JTextField jTxtFldSearchTitre;
    private javax.swing.JTextField jTxtFldTitreProb;
    private javax.swing.JTextField jTxtFldUID;
    // End of variables declaration//GEN-END:variables

    public JTable getjTableDemandes() {
        return jTableDemandes;
    }

    public JTextField getjTxtFldSearchTitre() {
        return jTxtFldSearchTitre;
    }
    public static void displayNotification(String message){
    	try {
			Thread.sleep(3000);
		} catch (InterruptedException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}	
        JTextPane edit = new JTextPane();
        final JFrame frame=new JFrame();
		frame.setSize(300,100);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setLayout(new GridBagLayout());
		frame.setForeground(Color.GRAY);
		frame.setUndecorated(true);
		frame.getContentPane().setBackground(Color.WHITE);
		frame.setLayout(new GridBagLayout());
		frame.setForeground(Color.GRAY);
		frame.getRootPane().setBorder(BorderFactory.createMatteBorder(2,2, 2, 2, Color.GREEN));
		frame.getContentPane().add(edit);
        GridBagConstraints constraints = new GridBagConstraints();
		constraints.gridx = 0;
		constraints.gridy = 0;
		constraints.weightx = 1.0f;
		constraints.weighty = 1.0f;
		constraints.insets = new Insets(5, 5, 5, 5);
		constraints.fill = GridBagConstraints.BOTH;
        constraints.gridx++;
 		constraints.weightx = 0f;
 		constraints.weighty = 0f;
 		constraints.fill = GridBagConstraints.NONE;
 		constraints.anchor = GridBagConstraints.NORTH;
 		JButton cloesButton = new JButton("X");
 		cloesButton.setMargin(new Insets(1, 4, 1, 4));
 		cloesButton.setFocusable(false);

		 try
		 {
		    // edit.setEditorKit(new MyEditorKit());
		     SimpleAttributeSet attrs=new SimpleAttributeSet();
		     StyleConstants.setAlignment(attrs,StyleConstants.ALIGN_LEFT);
		     StyledDocument doc=(StyledDocument)edit.getDocument();
		     doc.insertString(0,message,attrs);
		     doc.setParagraphAttributes(0,doc.getLength()-1,attrs,true);
		 }
		 catch (Exception ex)
		 {
		     ex.printStackTrace();
		 }
         
		 frame.add(cloesButton, constraints);

		 frame.setSize(frame.getPreferredSize());
		
		 Dimension scrSize = Toolkit.getDefaultToolkit().getScreenSize();// size of the screen
		 Insets toolHeight = Toolkit.getDefaultToolkit().getScreenInsets(frame.getGraphicsConfiguration());// height of the task bar
		 frame.setLocation(scrSize.width - frame.getWidth(), scrSize.height - toolHeight.bottom - frame.getHeight());
		 frame.setAlwaysOnTop(true);
         frame.show();
     
         
		cloesButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				frame.dispose();
			}
		});
		
		new Thread(){
			  @Override
			  public void run() {
			       try {
			              Thread.sleep(8000); // time after which pop up will be disappeared.
			              frame.dispose();
			       } catch (InterruptedException e) {
			              e.printStackTrace();
			       }
			  };
		}.start();
		
		Toolkit.getDefaultToolkit().beep();

    }
}
