/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.JFrameProblem.file;
import com.toedter.calendar.JDateChooser;
import entities.Probleme;
import java.awt.HeadlessException;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author asalhi
 */
public class JFrameEditProblem extends javax.swing.JFrame {

    /**
     * Creates new form JFrameEditProblem
     */
    JFrameProblem jFrameProblem;
    public static File file;
    public int num;
    public String filePath;
    public String fileName;
    private JDateChooser jDtChooserDeadline;

    public JFrameEditProblem(String title) throws HeadlessException {
        super(title);
    }

    public JFrameEditProblem() {

        initComponents();
        setTitle("Modification Demande");
        setBounds(250, 250, 1000, 700);
        jTxtFldIDProb.setVisible(false);
    }

    public JFrameEditProblem(JFrameProblem jFrameProblem) {
        this.jFrameProblem = jFrameProblem;

        initComponents();
        jTxtFldIDProb.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserModif = new javax.swing.JFileChooser();
        jPanelEditProblem = new javax.swing.JPanel();
        jPanelModif = new javax.swing.JPanel();
        jTxtFldMidifierDemande = new javax.swing.JTextField();
        jLabelTitreProb = new javax.swing.JLabel();
        jTxtFldTitreProb = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboCategorie = new javax.swing.JComboBox();
        jLabelDeadline = new javax.swing.JLabel();
        jLabelFichier = new javax.swing.JLabel();
        jTxtFldFichier = new javax.swing.JTextField();
        jBtnJoindreFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescriptionProb = new javax.swing.JTextArea();
        jBtnValider = new javax.swing.JButton();
        jLabelDescription = new javax.swing.JLabel();
        jTxtFldIDProb = new javax.swing.JTextField();
        jBtnAnnulerModif = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelModif.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTxtFldMidifierDemande.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jTxtFldMidifierDemande.setText(" Modifiez votre demande ");
        jTxtFldMidifierDemande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldMidifierDemandeActionPerformed(evt);
            }
        });

        jLabelTitreProb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelTitreProb.setText("Titre :");

        jTxtFldTitreProb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTxtFldTitreProb.setText(" ");
        jTxtFldTitreProb.setToolTipText("* Champ obligatoire");
        jTxtFldTitreProb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldTitreProbActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Catégorie :");

        jComboCategorie.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboCategorie.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"",  "Financier", "Administratif", "Technique", "Marketing","Social","Autre" }));
        jComboCategorie.setToolTipText("");

        jLabelDeadline.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelDeadline.setText("DeadLine :");

        jLabelFichier.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelFichier.setText("Fichier :");

        jTxtFldFichier.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTxtFldFichier.setText(" ");

        jBtnJoindreFile.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnJoindreFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/attach_file.png"))); // NOI18N
        jBtnJoindreFile.setText("Joindre");
        jBtnJoindreFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnJoindreFileActionPerformed(evt);
            }
        });

        jTextAreaDescriptionProb.setColumns(20);
        jTextAreaDescriptionProb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextAreaDescriptionProb.setRows(5);
        jTextAreaDescriptionProb.setToolTipText("* Champ obligatoire");
        jScrollPane1.setViewportView(jTextAreaDescriptionProb);

        jBtnValider.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/depos.png"))); // NOI18N
        jBtnValider.setText("Valider");
        jBtnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnValiderActionPerformed(evt);
            }
        });

        jLabelDescription.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelDescription.setText("Description :");

        jTxtFldIDProb.setText("IDP");
        jTxtFldIDProb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldIDProbActionPerformed(evt);
            }
        });

        jBtnAnnulerModif.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBtnAnnulerModif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cancel.png"))); // NOI18N
        jBtnAnnulerModif.setText("Annuler");
        jBtnAnnulerModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnnulerModifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelModifLayout = new javax.swing.GroupLayout(jPanelModif);
        jPanelModif.setLayout(jPanelModifLayout);
        jPanelModifLayout.setHorizontalGroup(
            jPanelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModifLayout.createSequentialGroup()
                .addGroup(jPanelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModifLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitreProb, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelModifLayout.createSequentialGroup()
                                .addComponent(jTxtFldTitreProb, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addGroup(jPanelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelModifLayout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jComboCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelModifLayout.createSequentialGroup()
                                        .addComponent(jLabelFichier, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTxtFldFichier)))
                                .addGap(18, 18, 18)
                                .addComponent(jBtnJoindreFile))))
                    .addGroup(jPanelModifLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jTxtFldMidifierDemande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModifLayout.createSequentialGroup()
                .addGap(0, 393, Short.MAX_VALUE)
                .addGroup(jPanelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModifLayout.createSequentialGroup()
                        .addComponent(jTxtFldIDProb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModifLayout.createSequentialGroup()
                        .addComponent(jBtnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jBtnAnnulerModif, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(320, 320, 320))))
        );
        jPanelModifLayout.setVerticalGroup(
            jPanelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModifLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jTxtFldMidifierDemande, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtFldTitreProb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTitreProb))
                    .addGroup(jPanelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(46, 46, 46)
                .addGroup(jPanelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelFichier, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtFldFichier, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnJoindreFile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModifLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelModifLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAnnulerModif, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jTxtFldIDProb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelEditProblemLayout = new javax.swing.GroupLayout(jPanelEditProblem);
        jPanelEditProblem.setLayout(jPanelEditProblemLayout);
        jPanelEditProblemLayout.setHorizontalGroup(
            jPanelEditProblemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 973, Short.MAX_VALUE)
            .addGroup(jPanelEditProblemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEditProblemLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelEditProblemLayout.setVerticalGroup(
            jPanelEditProblemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
            .addGroup(jPanelEditProblemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEditProblemLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEditProblem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEditProblem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtFldMidifierDemandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldMidifierDemandeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldMidifierDemandeActionPerformed

    private void jTxtFldTitreProbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldTitreProbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldTitreProbActionPerformed

    private void jBtnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnValiderActionPerformed
        if (jTxtFldTitreProb.getText() == null || jTxtFldTitreProb.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Le champ Titre est obligatoire", "", JOptionPane.WARNING_MESSAGE);
        } else if (jTextAreaDescriptionProb.getText() == null || jTextAreaDescriptionProb.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Le champ description est obligatoire", "", JOptionPane.WARNING_MESSAGE);
        } else if (jDtChooserDeadline.getDate() == null || jDtChooserDeadline.getDate().equals("")) {
            JOptionPane.showMessageDialog(this, "Le champ Deadline est obligatoire", "", JOptionPane.WARNING_MESSAGE);
        }else if (jDtChooserDeadline.getDate() != null && jDtChooserDeadline.getDate().before(new java.util.Date())) {
            JOptionPane.showMessageDialog(this, "Vous devez insérer une date valide", "", JOptionPane.WARNING_MESSAGE);
        }  else {
            try {
                
                new DAO.ProblemeDao().addToMedia(num + 1, fileName, filePath);
                new DAO.ProblemeDao().uploadFile(filePath,"C:\\xampp\\htdocs\\Pidev\\web\\uploads\\" + fileName );
                
                new DAO.ProblemeDao().update(new Probleme(Integer.valueOf(jTxtFldIDProb.getText()), jTxtFldTitreProb.getText(),
                         jTextAreaDescriptionProb.getText(), jDtChooserDeadline.getDate(), String.valueOf(num+1),
                          jComboCategorie.getSelectedItem().toString()));
                 

                jFrameProblem.setLay();

                JOptionPane.showMessageDialog(this, "Votre Demande a été modifiée avec succés !",
                        "Modification Demande", JOptionPane.INFORMATION_MESSAGE);

                this.hide();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Demande non Modifiée", "Modification Demande", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBtnValiderActionPerformed

    private void jTxtFldIDProbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldIDProbActionPerformed

    }//GEN-LAST:event_jTxtFldIDProbActionPerformed

    private void jBtnJoindreFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnJoindreFileActionPerformed
      int returnVal = jFileChooserModif.showOpenDialog(this);
        if (returnVal == jFileChooserModif.APPROVE_OPTION) {
            file = jFileChooserModif.getSelectedFile();

            filePath = file.getAbsolutePath();
            fileName = filePath.substring(filePath.lastIndexOf(File.separator) + 1);

            num = new DAO.ProblemeDao().getFileNumber();

            jTxtFldFichier.setText(fileName);
        }
        jFileChooserModif.setVisible(true);
    }//GEN-LAST:event_jBtnJoindreFileActionPerformed
   
    private void jBtnAnnulerModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnnulerModifActionPerformed
        this.hide();
    }//GEN-LAST:event_jBtnAnnulerModifActionPerformed

    /**
     * @param args the command line arguments 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEditProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEditProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEditProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEditProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                JFrameEditProblem frameEditionProb = new JFrameEditProblem();
                frameEditionProb.setBounds(250, 250, 1000, 700);
                frameEditionProb.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAnnulerModif;
    private javax.swing.JButton jBtnJoindreFile;
    private javax.swing.JButton jBtnValider;
    private javax.swing.JComboBox jComboCategorie;
    private javax.swing.JFileChooser jFileChooserModif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDeadline;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelFichier;
    private javax.swing.JLabel jLabelTitreProb;
    private javax.swing.JPanel jPanelEditProblem;
    private javax.swing.JPanel jPanelModif;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescriptionProb;
    private javax.swing.JTextField jTxtFldFichier;
    private javax.swing.JTextField jTxtFldIDProb;
    private javax.swing.JTextField jTxtFldMidifierDemande;
    private javax.swing.JTextField jTxtFldTitreProb;
    // End of variables declaration//GEN-END:variables

    public JButton getjBtnDeposer() {
        return jBtnValider;
    }

    public JButton getjBtnJoindreFile() {
        return jBtnJoindreFile;
    }

    public JComboBox getjComboCategorie() {
        return jComboCategorie;
    }

    public JDateChooser getjDtChooserDeadline() {
        return jDtChooserDeadline;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabelDeadline() {
        return jLabelDeadline;
    }

    public JLabel getjLabelDescription() {
        return jLabelDescription;
    }

    public JLabel getjLabelFichier() {
        return jLabelFichier;
    }

    public JLabel getjLabelTitreProb() {
        return jLabelTitreProb;
    }

    public JPanel getjPanelAjout() {
        return jPanelModif;
    }

    public JPanel getjPanelEditProblem() {
        return jPanelEditProblem;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTextArea getjTextArea1() {
        return jTextAreaDescriptionProb;
    }

    public JTextField getjTxtFldDeposerDemande() {
        return jTxtFldMidifierDemande;
    }

    public JTextField getjTxtFldFichier() {
        return jTxtFldFichier;
    }

    public JTextField getjTxtFldTitreProb() {
        return jTxtFldTitreProb;
    }

    public void setjBtnDeposer(JButton jBtnDeposer) {
        this.jBtnValider = jBtnDeposer;
    }

    public void setjBtnJoindreFile(JButton jBtnJoindreFile) {
        this.jBtnJoindreFile = jBtnJoindreFile;
    }

    public void setjComboCategorie(JComboBox jComboCategorie) {
        this.jComboCategorie = jComboCategorie;
    }

    public void setjDtChooserDeadline(JDateChooser jDtChooserDeadline) {
        this.jDtChooserDeadline = jDtChooserDeadline;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public void setjLabelDeadline(JLabel jLabelDeadline) {
        this.jLabelDeadline = jLabelDeadline;
    }

    public void setjLabelDescription(JLabel jLabelDescription) {
        this.jLabelDescription = jLabelDescription;
    }

    public void setjLabelFichier(JLabel jLabelFichier) {
        this.jLabelFichier = jLabelFichier;
    }

    public void setjLabelTitreProb(JLabel jLabelTitreProb) {
        this.jLabelTitreProb = jLabelTitreProb;
    }

    public void setjPanelAjout(JPanel jPanelAjout) {
        this.jPanelModif = jPanelAjout;
    }

    public void setjPanelEditProblem(JPanel jPanelEditProblem) {
        this.jPanelEditProblem = jPanelEditProblem;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.jTextAreaDescriptionProb = jTextArea1;
    }

    public void setjTxtFldDeposerDemande(JTextField jTxtFldDeposerDemande) {
        this.jTxtFldMidifierDemande = jTxtFldDeposerDemande;
    }

    public void setjTxtFldFichier(JTextField jTxtFldFichier) {
        this.jTxtFldFichier = jTxtFldFichier;
    }

    public void setjTxtFldTitreProb(JTextField jTxtFldTitreProb) {
        this.jTxtFldTitreProb = jTxtFldTitreProb;
    }

    public JTextField getjTxtFldIDProb() {
        return jTxtFldIDProb;
    }
}
